if (!require("cluster")) install.packages("cluster")
library(cluster)

library(readr)
dataset <- read_csv("C:/Users/emont/OneDrive/Escritorio/Tesis/MILP/Datasets/Datasets/Small/cancer.csv")

X <- dataset[, 3:32]
y <- dataset$diagnosis

k = length(table(y))

# Compute the distance matrix
if (!require("proxy")) install.packages("proxy")
library(proxy)
D <- proxy::dist(as.matrix(X), method = "cosine")
D = as.matrix(D)
distance = D

#===========================================================================================================
# K-MEDOIDS ALGORITHM PROCESS

r <- nrow(D) # Total number of instances

cl = pam(X, k)
label_pred = cl$cluster

#================================================================================================================
X_mat <- as.matrix(X)
X_norms <- sqrt(rowSums(X_mat^2)) + 1e-10
X_norm <- X_mat / X_norms

# Compute centroids generated by K-Medoids
u_labels <- sort(unique(label_pred))
centroids <- matrix(0, nrow = length(u_labels), ncol = ncol(X_mat))
for(i in seq_along(u_labels)) {
  mask <- (label_pred == u_labels[i])
  if(sum(mask) == 1) centroids[i,] <- X_mat[mask,] 
  else centroids[i,] <- colMeans(X_mat[mask,])
}

# Compute Cosine Distances (Point-to-Centroid)
c_norms <- sqrt(rowSums(centroids^2)) + 1e-10
c_norm <- centroids / c_norms
dists <- 1 - tcrossprod(X_norm, c_norm)
dists[dists < 0] <- 0

# Compute a(i) and b(i)
idx <- cbind(1:nrow(X), match(label_pred, u_labels))
a_i <- dists[idx]            # Distance to its own centroid
dists[idx] <- Inf            # Ignore own centroid to find nearest neighbor
b_i <- apply(dists, 1, min)  # Distance to the nearest neighboring centroid

sil_compatible <- mean((b_i - a_i) / pmax(a_i, b_i), na.rm = TRUE)

# 4. Final Metrics
cat("--------------------------------------------------\n")
cat("Silhouette (Centroid-based Logic):", sil_compatible, "\n")
cat("ARI                            :", ARI(y, label_pred), "\n")
cat("AMI                            :", AMI(y, label_pred), "\n")
cat("NMI                            :", NMI(y, label_pred), "\n")
cat("--------------------------------------------------\n")

# Counts
cat("\nGround Truth Groups:\n"); print(table(y))
cat("\nK-Medoids Groups:\n"); print(table(label_pred))